In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[ 'the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation 
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1442, 6465, 7653, 8129],
 [1442, 6465, 7653, 5531],
 [1442, 7813, 7653, 6100],
 [5185, 1586, 7398, 8221, 992],
 [5185, 1586, 7398, 8221, 4797],
 [5788, 1442, 9865, 7653, 9860],
 [1933, 7940, 8780, 8221]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1442 6465 7653 8129]
 [   0    0    0    0 1442 6465 7653 5531]
 [   0    0    0    0 1442 7813 7653 6100]
 [   0    0    0 5185 1586 7398 8221  992]
 [   0    0    0 5185 1586 7398 8221 4797]
 [   0    0    0 5788 1442 9865 7653 9860]
 [   0    0    0    0 1933 7940 8780 8221]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile('adam','mse')

In [11]:
# Force the model to build
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 1442, 6465, 7653, 8129])

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [-0.04324697, -0.00126924, -0.03142124,  0.03779432,
          0.03245499, -0.01163344,  0.04537332,  0.0282243 ,
          0.00029932,  0.00198002],
        [-0.03080312,  0.00759071,  0.02548352, -0.0253076 ,
         -0.0069754 , -0.00707697,  0.04699035,  0.01483646,
          0.01825916,  0.01328451],
        [-0.02555807,  0.01870301,  0.01878046, -0.0

In [14]:

model.predict(np.expand_dims(embedded_docs[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[[ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [ 0.04895771,  0.01408396,  0.04466465, -0.03237549,
          0.02190996,  0.01537857,  0.02288908,  0.03131602,
         -0.00629278,  0.0194953 ],
        [-0.04324697, -0.00126924, -0.03142124,  0.03779432,
          0.03245499, -0.01163344,  0.04537332,  0.0282243 ,
          0.00029932,  0.00198002],
        [-0.03080312,  0.00759071,  0.02548352, -0.0253076 ,
         -0.0069754 , -0.00707697,  0.04699035,  0.01483646,
          0.01825916,  0.01328451],
        [-0.02555807,  0.01870301,  0.01878046, -0.0